name: ildiz_kitoblari
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_math_fork: ^0.7.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  introduction_screen: ^3.1.14
  change_app_package_name: ^1.5.0
  flutter_spinkit: ^5.2.1
  dio: ^5.8.0+1
  pull_to_refresh: ^2.0.0
  flutter_screenutil: ^5.9.3
  flaticon: ^0.0.1
  flutter_tabler_icons: ^1.21.0
  screen_brightness: ^2.1.3
  webview_flutter: ^4.11.0

  flutter_svg: ^2.1.0
  adaptive_theme: ^3.7.0
  mask_text_input_formatter: ^2.9.0
  carousel_slider: ^5.0.0
  flutter_html: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_swiper_view: ^1.1.8
  photo_view: ^0.15.0
  image_picker: ^1.0.7
  permission_handler: ^12.0.0+1
  intl: ^0.20.2
  skeletonizer: ^1.4.3
  text_scroll: ^0.2.0
  fading_edge_scrollview: ^4.1.1
  badges: ^3.1.2
  disposable_cached_images: ^1.2.1
  epubx: ^4.0.0
  http: ^1.2.1

  flutter_inappwebview: ^6.0.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_plugin_android_lifecycle: ^2.0.28
  flutter_epub_viewer: ^1.2.1
  just_audio: ^0.10.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/svgImages/
    - assets/icon/

  fonts:
    #book fonts
    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya.ttf
    - family: Amazon Ember
      fonts:
        - asset: assets/fonts/Amazon-Ember-Regular.ttf
    - family: Atkinson Hyperlegible
      fonts:
        - asset: assets/fonts/AtkinsonHyperlegible-Regular.ttf
    - family: Bitter Pro
      fonts:
        - asset: assets/fonts/BitterPro-Regular.ttf
    - family: Bookerly
      fonts:
        - asset: assets/fonts/Bookerly.ttf
    - family: Droid Sans
      fonts:
        - asset: assets/fonts/DroidSans.ttf
    - family: EB Garamond
      fonts:
        - asset: assets/fonts/EBGaramond-Var.ttf
    - family: Gentium Book Plus
      fonts:
        - asset: assets/fonts/GentiumBookPlus-Regular.ttf
    - family: Halant
      fonts:
        - asset: assets/fonts/Halant-Regular.ttf
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
    - family: LinLibertine
      fonts:
        - asset: assets/fonts/LinLibertine-Regular.ttf
    - family: Literata
      fonts:
        - asset: assets/fonts/Literata-Var.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Var.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Var.ttf